### ISSUE TITLE
Title of UI Page is incorrect

### ISSUE THREAD

**Issue by bacon274** [DigitalShoestringSolutions/DowntimeMonitoring#3]
says "scrap monitoring" should be "downtime monitoring"

**Comment by Greg-Hawkridge** [comment]
Does it say "scrap monitoring" or "Fault Tracking". From the [code](https://github.com/DigitalShoestringSolutions/DowntimeMonitoring/blob/c224549dcfdcaa643b22116328bbb805a96b74fe/stoppage_dc/code/public/index.html#L9C1-L9C1) it should be fault tracking
